
CREATE USER SPORTSMANAGEMENT IDENTIFIED BY SAIKIRAN12 ; 

GRANT ALL PRIVILEGES TO SPORTSMANAGEMENT;


--------------------------------------------------------
--  File created - Saturday-June-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINLOGINDETAILS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."ADMINLOGINDETAILS" 
   (	"USERNAME" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE)
   ) 
--------------------------------------------------------
--  DDL for Table ANNOUNCEMENTS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."ANNOUNCEMENTS" 
   (	"DATEOFADD" VARCHAR2(20 BYTE), 
	"MATTER" VARCHAR2(300 BYTE)
   ) 
--------------------------------------------------------
--  DDL for Table BADMINTIONPLAYERSDETAILS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(9,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"YEAR" NUMBER(4,0), 
	"CONTACT" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(10,0), 
	"SPORT" VARCHAR2(20 BYTE), 
	"BRANCH" VARCHAR2(20 BYTE)
   )
--------------------------------------------------------
--  DDL for Table CRICKETPLAYERSDETAILS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(9,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"YEAR" NUMBER(4,0), 
	"CONTACT" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(10,0), 
	"SPORT" VARCHAR2(20 BYTE), 
	"BRANCH" VARCHAR2(20 BYTE)
   )
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."EVENTS" 
   (	"DATEOFADD" VARCHAR2(20 BYTE), 
	"MATTER" VARCHAR2(300 BYTE)
   ) 
--------------------------------------------------------
--  DDL for Table HOCKEYPLAYERSDETAILS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(9,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"YEAR" NUMBER(4,0), 
	"CONTACT" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(10,0), 
	"SPORT" VARCHAR2(20 BYTE), 
	"BRANCH" VARCHAR2(20 BYTE)
   ) 
--------------------------------------------------------
--  DDL for Table STUDENTLOGINDETAILS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."STUDENTLOGINDETAILS" 
   (	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) 
--------------------------------------------------------
--  DDL for Table VOLLEYBALLPLAYERSDETAILS
--------------------------------------------------------

  CREATE TABLE "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(9,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"YEAR" NUMBER(4,0), 
	"CONTACT" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(10,0), 
	"SPORT" VARCHAR2(20 BYTE), 
	"BRANCH" VARCHAR2(20 BYTE)
   ) 


Insert into SPORTSMANAGEMENT.ADMINLOGINDETAILS (USERNAME,PASSWORD) values ('admin','admin');

Insert into SPORTSMANAGEMENT.ANNOUNCEMENTS (DATEOFADD,MATTER) values ('1/1/1','lockdown 4.0');

Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1412,'sa1i@gmail.com','m',2,4523,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',14122,'sa12i@gmail.com','m',2,45232,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',141222,'sa122i@gmail.com','m',2,452322,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1412222,'sa1222i@gmail.com','m',2,4523222,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1412232,'sa1232i@gmail.com','m',2,4523223,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1412233,'sa3232i@gmail.com','m',2,4523233,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1412235,'jjjjjjjjjjjjjjjjsasasasa3232i@gmail.com','m',2,4523235,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1412236,'jjjjjjjjjjjjjjjjasasasa3232i@gmail.com','m',2,4523236,'Address','Palakollu','w',7,'badmintion','cse');
Insert into SPORTSMANAGEMENT.BADMINTIONPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',14122347,'jjjjjjjjjjjjjjjjasasa323i@gmail.com','m',2,45232367,'Address','Palakollu','w',7,'badmintion','cse');

Insert into SPORTSMANAGEMENT.CRICKETPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('s',1,'j@gmail.com','m',3,1,'Address','s','s',1,'cricket','cse');
Insert into SPORTSMANAGEMENT.CRICKETPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('vamsi',180040028,'vamsikrishnassh007@gmail.com','m',2020,70142589,'1 town','ijayawada','krishna',534266,'cricket','M.Tech');
Insert into SPORTSMANAGEMENT.CRICKETPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('rohith',180030653,'rohithkaza@gmail.com','m',2,21,'Address','s','s',1,'cricket','CSE');
Insert into SPORTSMANAGEMENT.CRICKETPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('saikiran',180031265,'jaddusaikiran9978@gmail.com','m',2,1,'Address','l','l',1,'cricket','CSE');
Insert into SPORTSMANAGEMENT.CRICKETPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('safia',180030583,'safia@gmail.com','f',2,1,'Address','2','2',2,'cricket','cse');
Insert into SPORTSMANAGEMENT.CRICKETPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('kalyani',180031162,'kalyani@gmail.com','f',2,2,'Address','2','2',2,'cricket','cse');

Insert into SPORTSMANAGEMENT.EVENTS (DATEOFADD,MATTER) values ('2020-12-12','testing');
Insert into SPORTSMANAGEMENT.EVENTS (DATEOFADD,MATTER) values ('2020-12-13','Again testing');
Insert into SPORTSMANAGEMENT.EVENTS (DATEOFADD,MATTER) values ('1220-12-12','Last time testing sorry!!!');
Insert into SPORTSMANAGEMENT.EVENTS (DATEOFADD,MATTER) values ('0012-12-12','Address');

Insert into SPORTSMANAGEMENT.HOCKEYPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('a',101011,'s@gmail.com','m',2,1241,'Address','p','WEST',4,'hockey','CSE');
Insert into SPORTSMANAGEMENT.HOCKEYPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('a',1010112,'s@gmail.com','m',2,12411,'Address','p','WEST',4,'hockey','CSE');
Insert into SPORTSMANAGEMENT.HOCKEYPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('a',1010113,'s@gmail.com','m',2,12412,'Address','p','WEST',4,'hockey','CSE');
Insert into SPORTSMANAGEMENT.HOCKEYPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('a',1010114,'s@gmail.com','m',2,124100,'Address','p','WEST',4,'hockey','CSE');

Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('saikiran12','saikiran');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('saikiran12','saikiran12');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180040028','vamsi');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030393','dinesh');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180030583','safia');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180031162','kalyani');
Insert into SPORTSMANAGEMENT.STUDENTLOGINDETAILS (USERNAME,PASSWORD) values ('180031265','saikiran12');

Insert into SPORTSMANAGEMENT.VOLLEYBALLPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('saikiran',1,'jaddusaikiran9978@gmail.com','m',-1,1,'Address','pko','krishna',6,'volleyball','CSE');
Insert into SPORTSMANAGEMENT.VOLLEYBALLPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('dinesh',180030393,'dineshthota@gmail.com','m',2,9988049173,'savargudem','gannavaram','krishna',51426,'volleyball','cse');
Insert into SPORTSMANAGEMENT.VOLLEYBALLPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('saikiran',2,'iran9978@gmail.com','m',2,10,'Address','pko','krishna',6,'volleyball','CSE');
Insert into SPORTSMANAGEMENT.VOLLEYBALLPLAYERSDETAILS (NAME,ID,EMAIL,GENDER,YEAR,CONTACT,ADDRESS,CITY,DISTRICT,PINCODE,SPORT,BRANCH) values ('saikiran',3,'n9978@gmail.com','m',3,11,'Address','pko','krishna',6,'volleyball','CSE');
--------------------------------------------------------
--  DDL for Index PK_V
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPORTSMANAGEMENT"."PK_V" ON "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" ("ID") 
 
--------------------------------------------------------
--  DDL for Index PK_H
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPORTSMANAGEMENT"."PK_H" ON "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" ("ID") 
 
--------------------------------------------------------
--  DDL for Index PK_B
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPORTSMANAGEMENT"."PK_B" ON "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" ("ID") 
  
--------------------------------------------------------
--  DDL for Index PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPORTSMANAGEMENT"."PK" ON "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" ("ID") 
  
--------------------------------------------------------
--  Constraints for Table ADMINLOGINDETAILS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."ADMINLOGINDETAILS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."ADMINLOGINDETAILS" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BADMINTIONPLAYERSDETAILS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" ADD CONSTRAINT "PK_B" PRIMARY KEY ("ID");
 
  ALTER TABLE "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" ADD UNIQUE ("ID", "EMAIL");
 
  ALTER TABLE "SPORTSMANAGEMENT"."BADMINTIONPLAYERSDETAILS" MODIFY ("CONTACT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOLLEYBALLPLAYERSDETAILS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" ADD CONSTRAINT "PK_V" PRIMARY KEY ("ID");
 
  ALTER TABLE "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" ADD UNIQUE ("ID", "EMAIL");
 
  ALTER TABLE "SPORTSMANAGEMENT"."VOLLEYBALLPLAYERSDETAILS" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOCKEYPLAYERSDETAILS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" ADD CONSTRAINT "PK_H" PRIMARY KEY ("ID");
 
  ALTER TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" ADD UNIQUE ("ID", "EMAIL");
 
  ALTER TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."HOCKEYPLAYERSDETAILS" MODIFY ("CONTACT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."EVENTS" MODIFY ("DATEOFADD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTLOGINDETAILS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."STUDENTLOGINDETAILS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."STUDENTLOGINDETAILS" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CRICKETPLAYERSDETAILS
--------------------------------------------------------

  ALTER TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" ADD CONSTRAINT "PK" PRIMARY KEY ("ID");
 
  ALTER TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" ADD UNIQUE ("ID", "EMAIL");
 
  ALTER TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SPORTSMANAGEMENT"."CRICKETPLAYERSDETAILS" MODIFY ("CONTACT" NOT NULL ENABLE);
